project:
  type: website

website:
  title: "Vinay Jose"
  description: "a Software Engineer _delving_ into AI"
  favicon: favicon/favicon-32x32.png
  twitter-card: true
  site-url: https://vinayjose.com/blog/
  open-graph: true
  search: false
  navbar:
    title: false
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about
      - text: Projects
        href: projects
    right:
      - icon: twitter
        href: https://twitter.com/vinayjose
      - icon: linkedin
        href: https://linkedin.com/kxvinayjose
      - icon: github
        href: https://github.com/vinay-jose
  page-footer: 
    center: "Copyright 2024, Vinay Jose" 
format:
  html:
    theme: lux
    linkcolor: "#168873"
    css: styles.css
    urlExtension: html



