project:
  type: website

website:
  title: "Vinay Jose"
  navbar:
    title: false
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Projects
        href: projects.qmd
    right:
      - icon: twitter
        href: https://twitter.com/vinayjose
      - icon: linkedin
        href: https://linkedin.com/kxvinayjose
      - icon: github
        href: https://github.com/vinay-jose
format:
  html:
    theme: cosmo
    css: styles.css



